server:
  port: 8081
  context-path: /activity
  session:
    timeout: 10
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti_project?characterEncoding=utf8&useSSL=true
    username: root
    password: 1234567
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  show-sql: true

